# PostgreSQL Data Source Configuration
spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Token secret
dineflex.jwt.secret=${DINEFLEX_JWT_SECRET}

# Required for Docker container on Render
server.port=${PORT:8080}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid,profile,email

dineflex.oauth2.redirect-uri=https://dine-flex-frontend.vercel.app/oauth2/redirect

logging.level.org.springframework.security=DEBUG